on: [ push ]

permissions:
  contents: read

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: qq253498229/github-actions-template@v1.4
        with:
          who-to-greet: 'Mona the Octocat'
