on: [ push ]

permissions:
  contents: write

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: qq253498229/github-actions-template@v1.4
        with:
          who-to-greet: 'Mona the Octocat'
      - run: |
          pwd
          la -al
          zip -r dist.zip dist
      - if: github.ref_type == 'tag'
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
